FROM postgres:13

# Set environment variables
ENV POSTGRES_USER=saleor
ENV POSTGRES_PASSWORD=saleor
ENV POSTGRES_DB=saleor

# Copy initialization scripts
COPY ./replica_user.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432

# Set the default command
CMD ["postgres"]
